### ISSUE TITLE
Got at least one module with raw mappings

### ISSUE THREAD

**Issue by oleg-deezus** [mhzed/react-native-sm-transformer#3]
Hi! I got this error
```
Error: Got at least one module with raw mappings, but C:\Users\Oleg\vezde\dist\components\Main.js has a full source map
    at resolver.wrapModule.then (C:/Users/Oleg/vezde/node_modules/react-native/packager/src/Bundler/Bundle.js:105:17)
(node:2176) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1054): Error: Got at least one module with raw mappings, but C:\Users\Oleg\vezde\dist\components\Main.js has a full source map
(node:2176) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Elemecca** [comment]
It looks like since facebook/react-native@0849f84df26e4c56f5763375363bae90d94015fe (which landed in v0.42.0) the React Native Packager by default uses a proprietary, purportedly more efficient format to transport source maps through the transformer from Babel to the bundler. It doesn't support bundling when some modules use that format (which they call "raw") and some use real source maps (which they call "full"), hence the `Got at least one module with raw mappings, but <file> has a full source map` error when this transformer produces a module with a real source map. The message `Got at least one module with a full source map, but <file> has raw mappings` is also possible and means the same thing except that the modules loaded in a different order.

The default transformer will generate full source maps when the `generateSourceMaps` bundle option is true and raw source maps otherwise. For the dev server (i.e. `react-native start`), that option will be set if any of the query parameters `minify=true`, `dev=false`, or `babelSourcemap=true` are set on the HTTP request for the bundle file. Of those, `babelSourcemap=true` would be best as a workaround as it has no other effects. Unfortunately I don't know how to get the application to set that parameter.

This issue can therefore be worked around by shaking the device to open the development menu, tapping "Dev Settings", and ensuring that the "JS Minify" option is enabled. That will unfortunately make bundling performance moderately worse.

**Comment by mhzed** [comment]
Thanks for the comment and workaround.

**Comment by haha370104** [comment]
But it seems that there is no "Dev Settings" option in iOS development menu...
